### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by kjaymiller** [sandiegopython/pythonsd-django#116]
This project currently doesn't have a Code of Conduct. My assumption is that this repo would adhere to the code of conduct of the community. There are many ways to specify the code of conduct including setting the code of conduct at the org level.

**Comment by davidfischer** [comment]
I think the repo should probably use the SD python code. How do you add that to the repo or org?

**Comment by kjaymiller** [comment]
To add it to the org... You would just add a markdown copy of it to a repo called `.github`

Here is an example - https://github.com/Python-Community-News/.github

**Comment by davidfischer** [comment]
This has been added: https://github.com/sandiegopython/.github

**Comment by davidfischer** [comment]
I think we're good here.
