### ISSUE TITLE
Remove Microsoft from Sponsors Page

### ISSUE THREAD

**Issue by kjaymiller** [sandiegopython/pythonsd-django#127]
We won't have new sponsorship from Microsoft in terms of Food.

Please remove them from the sponsors list or add them to a previous sponsors list.

**Comment by davidfischer** [comment]
No worries. We may have some new sponsors and I might try to see if Cloudflare will still do pizza for the meetup on Thursday.

**Comment by davidfischer** [comment]
I'm going to replace Microsoft on the website with Neo4j who is going to sponsor food and drinks at the meetup.
