### ISSUE TITLE
Add XML sitemap

### ISSUE THREAD

**Issue by JackBerezhnov** [sandiegopython/pythonsd-django#129]
This website is not big, but it would be nice to have an XML sitemap for better SEO.

I used [xml-sitemaps.com ](https://www.xml-sitemaps.com/) which generated XML sitemap.
I will upload one in discord general chat, and you can upload it on your website if you want or I will create a pull request later.
Also, you can add directly to [Google Search Console](https://search.google.com/search-console/about) for not waiting when Google will find your sitemap.

I hope it helps.

Best regards,
Jack

**Comment by davidfischer** [comment]
I'm on board with a sitemap. Just a note that there is a [Django sitemap framework](https://docs.djangoproject.com/en/4.2/ref/contrib/sitemaps/) if that proves useful.

The homepage actually automatically updates itself based on meetup and youtube periodically and should probably be set to weekly or more frequent. Other pages are updated more slowly and set to monthly or less frequently.
