### ISSUE TITLE
Suggestion: store videos in the database

### ISSUE THREAD

**Issue by Jer-Pha** [sandiegopython/pythonsd-django#147]
(I'm not sure if there's a better place for suggestions)

Has there been thought of storing the video data in the database, utilizing a Django model with title, id, url, date published, and category fields? This would just need a (weekly? monthly?) task in Heroku Scheduler to check for and add new videos. The only manual update would be categorizing each video (e.g. Meetup, Workshop, etc.).

Depending on the impact to the database, the video description could also be added as a TextField to allow Postgres [full text search](https://docs.djangoproject.com/en/5.0/ref/contrib/postgres/search/). There's also the possibility of tags using ManytoManyField and a Tags model. This would be more manual work for new videos, though.

Obviously, this is overkill right now. The thought behind this suggestion is that it will allow for future implementation of a video page with sort/filter/search functionality along with easy pagination using Django's [Paginator](https://docs.djangoproject.com/en/5.0/ref/paginator/).

**Comment by davidfischer** [comment]
This is a fine place for suggestions.

I think this is a pretty good idea if we can do it without adding a bunch of extra infrastructure to have a task queue. Basically we just need to parse the YouTube feed every few minutes and compare it to the database. Loading the video from the DB instead of the feed directly would definitely have some nice performance gains and avoid awkward caching. The same could probably apply to the meetup.com feed.

> This would just need a (weekly? monthly?) task in Heroku Scheduler to check for and add new videos.

Just a note that the site is deployed to fly.io now and not Heroku. It used to be on Heroku but we moved it. Are there some docs that still say Heroku? If so, we should update it.

**Comment by Jer-Pha** [comment]
I'm not sure if the XML has a way to loop through all videos or if it's only the first page. In a past project, I used the YouTube API to add thousands of videos from a channel to a database. Here's a modified version of what that looks like: [youtube_api_check.txt](https://github.com/sandiegopython/pythonsd-django/files/15424821/youtube_api_check.txt)
 (apparently .py files can't be attached here).


The downside to this is that the [search](https://developers.google.com/youtube/v3/docs/search/list) endpoint does not include the video's description. So there would need to be a second call using the [videos](https://developers.google.com/youtube/v3/docs/videos/list) endpoint. I added this in the .txt file, but it's untested.

> Basically we just need to parse the YouTube feed every few minutes and compare it to the database. 

I'm not familiar with fly.io but I'm assuming they have something similar to PythonAnywhere's scheduled tasks (or maybe a cron job?). For my previous project, I had the task run every hour to check for new videos (the API's quota didn't allow for it to be more often). If this is done with XML, every 5 minutes would be fine. The loop could just be broken as soon as the first .exists() returns True (for the very unlikely occurrence of more than one new video between checks).

There's a few mentions of Heroku, I'll submit a PR for those.

**Comment by davidfischer** [comment]
I think the XML feed is for just recent videos. It isn't a full API. We'd have to use the YouTube API for that as you suggested.

However, I'm not sure we need it unless we're planning to build some alternative way to search our videos/streams on YouTube or we want to display all our videos for some reason. I'm not sure we need that. Really we just need to display recent videos which is exactly what the RSS feed does. I think we need to think about the experience we're trying to build.

I haven't done a lot with Fly.io so I'm not sure how you do scheduled tasks. We could of course run something like `celerybeat`, but that will probably take us above the free tier.

**Comment by Jer-Pha** [comment]
That's fair. My thinking was more along the lines of "just in case we need the data" which is a dangerous game to play. Long term, I was thinking of a list of all videos with pagination to keep interested users on the site instead of navigating away (to YouTube) but it really doesn't make sense to try to build a search/filter system just for that reason when YouTube will do it better.

If there's no way to automate the task without increasing the tier then it's not really worth it. The performance difference wouldn't be noticeable to most users. As long as the need for videos stays at 15 or less recent videos then the current setup is good.
