### ISSUE TITLE
Upgrade to Django 4.2

### ISSUE THREAD

**Issue by davidfischer** [sandiegopython/pythonsd-django#154]
I like sticking with [LTS versions of Django](https://www.djangoproject.com/download/#supported-versions), but we are currently on an unsupported version. This is probably just a matter of upgrading Django and seeing if anything breaks and fixing those things. Some dependencies may also need to be upgraded.

**Comment by Jer-Pha** [comment]
Looking at this [article](https://medium.com/django-unleashed/upgrade-django32-to-django42-d581d272540e), I'm not seeing anything that was deprecated/changed from 3.2 to 4.2 that the site is currently using. The note about collectstatic near the bottom might be an issue. I'm not sure what version of PostgreSQL the site uses, but it looks like it would need to be 12+ with Django 4.2.

**Comment by davidfischer** [comment]
Our Fly.io setup is using postgres v14.4. I don't think collectstatic will be an issue but probably needs a test.

**Comment by Jer-Pha** [comment]
DEFAULT_FILE_STORE is being added to `settings/prod.py` in #158. This is [deprecated in 4.2](https://docs.djangoproject.com/en/5.0/ref/settings/#default-file-storage) and will need to be changed to [STORAGES](https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-STORAGES) when Django is upgraded.

I just noticed that [STATICFILES_STORAGE](https://github.com/sandiegopython/pythonsd-django/blob/1de8add84fb52d7dee3cceb2000143dc4f3efc30/config/settings/base.py#L112) is also [deprecated in 4.2](https://docs.djangoproject.com/en/5.0/ref/settings/#staticfiles-storage) and needs to be changed to STORAGES too.
