### ISSUE TITLE
<title> does not change when navigating to different pages

### ISSUE THREAD

**Issue by Jer-Pha** [sandiegopython/pythonsd-django#157]
Waiting for the Organizers page to be up and running before submitting a PR for this.

**Comment by davidfischer** [comment]
Good thought on waiting. The fix here should be straight-forward. There's a template block for the title so we just need to define that block in the code-of-conduct and organizers template.

https://github.com/sandiegopython/pythonsd-django/blob/1de8add84fb52d7dee3cceb2000143dc4f3efc30/pythonsd/templates/pythonsd/base.html#L11
