### ISSUE TITLE
Build our own Slack invite

### ISSUE THREAD

**Issue by davidism** [sandiegopython/pythonsd-django#46]
Right now, we use https://github.com/rauchg/slackin to send out invites to our Slack server. It's hosted on a free Heroku dyno which is very slow to spin up when the first users go to it during meetups.

Since we're going full Django web app now, we should have a page like `/slack/invite` that does what SlackIn was doing for us. Take the user's email as well as a confirmation that they've read the Code of Conduct (and maybe a short intro about the channels we have), then generate an email with a Slack invite.

One question is whether we have an SMTP server to send mail with. I'm not sure what SlackIn uses.

I'm happy to help anyone who's interested in working on this with figuring out Slack integration, mail configuration, etc.

**Comment by davidfischer** [comment]
> One question is whether we have an SMTP server to send mail with. I'm not sure what SlackIn uses.

The free plan on Heroku (through Mailgun or SendGrid) will have *way* more than we use.

**Comment by davidfischer** [comment]
This should be reasonably easy to get a simple version going but we can make this more complicated if needed. At the most basic level, we just need the following steps:

- Display user's email form with optional captcha
- Call the [API to invite the user](https://api.slack.com/methods/admin.users.invite). Display errors to the user or tell them to check their email.
- User receives email and joins the Slack workspace

Alternatively, there's a few off-the-shelf Django apps for this ([SlackInvite](https://github.com/sanchagrins/SlackInvite), [django-slack-invitation](https://github.com/giginet/django-slack-invitation)) as well although they look like they might need light adapting. They're pretty straight-forward too so I lean toward writing a quick form.

**Comment by davidfischer** [comment]
Switched to discord. Closing...
